[package]
name = "tamichat"
version = "0.1.0"
authors = ["Wissotsky <Wissotsky@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.0", features = [] }
prost = "0.14.1"
reqwest = "0.12.24"
base64 = "0.22"
ed25519-dalek = { version = "3.0.0-pre.1", features = ["rand_core"] }
tracing = "0.1.41"
rand = "0.9.2"
getrandom = { version = "0.3.4", features = ["wasm_js"] }
chrono = { version = "0.4.42", features = ["wasmbind"] }
gloo-timers = { version = "0.3", features = ["futures"] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[build-dependencies]
prost-build = "0.14.1"
